# Linear Algebra

In [1]:
# Library
import numpy as np

### Matrices

In [2]:
matrices = np.array([[1,2,3],[-4,5,6]])

In [3]:
matrices

array([[ 1,  2,  3],
       [-4,  5,  6]])

### Scalars

In [4]:
scalars = 8


In [5]:
scalars

8

### Scalar Array

In [6]:
s_array = np.array(5)

### Vectors

In [7]:
vectors = np.array([7,-8,0])

In [8]:
vectors

array([ 7, -8,  0])

## Data Types

In [9]:
type(matrices)

numpy.ndarray

In [10]:
type(scalars)

int

In [11]:
type(vectors)

numpy.ndarray

In [12]:
type(s_array)

numpy.ndarray

## Data Shapes

In [13]:
matrices.shape

(2, 3)

In [14]:
scalars.shape

AttributeError: 'int' object has no attribute 'shape'

In [15]:
vectors.shape

(3,)

In [16]:
s_array.shape

()

## Creating a column vector

In [17]:
vectors.reshape(1,3)

array([[ 7, -8,  0]])

In [18]:
vectors.reshape(3,1)

array([[ 7],
       [-8],
       [ 0]])

In [19]:
matrices + scalars

array([[ 9, 10, 11],
       [ 4, 13, 14]])

In [20]:
matrices + s_array

array([[ 6,  7,  8],
       [ 1, 10, 11]])

In [21]:
vectors + scalars

array([15,  0,  8])

In [22]:
vectors + s_array

array([12, -3,  5])

In [23]:
matrices + vectors

array([[ 8, -6,  3],
       [ 3, -3,  6]])

# Tensors

In [24]:
m1 = np.array([[1,2,3],[-4,-5,-6]])
m1

array([[ 1,  2,  3],
       [-4, -5, -6]])

In [25]:
m2 = np.array([[7,8,9],[0,1,2]])
m2

array([[7, 8, 9],
       [0, 1, 2]])

In [26]:
t = np.array([m1,m2])
t

array([[[ 1,  2,  3],
        [-4, -5, -6]],

       [[ 7,  8,  9],
        [ 0,  1,  2]]])

In [27]:
t.shape

(2, 2, 3)

## Create Tensor

In [28]:
tensor = np.array([[[ 1, 2, 3], [4, 5, 6]], [[ 7,  8,  9], [ -3,  -2, -1]]])

In [29]:
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [-3, -2, -1]]])

## Addition Matrices

In [30]:
m1 + m2

array([[ 8, 10, 12],
       [-4, -4, -4]])

## Subtraction Matrices

In [31]:
m1 - m2

array([[-6, -6, -6],
       [-4, -6, -8]])

In [32]:
m3 = np.array([[8,10],[11,12],[15,18]])
m3

array([[ 8, 10],
       [11, 12],
       [15, 18]])

In [33]:
m4 = np.array([[6,8],[-5,10],[-18,20]])
m4

array([[  6,   8],
       [ -5,  10],
       [-18,  20]])

In [34]:
m3 - m4

array([[ 2,  2],
       [16,  2],
       [33, -2]])

## Addition Vectors

In [35]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [36]:
v1 + v2

array([6, 6, 6, 6, 6])

## Subtraction Vectors

In [37]:
v1 - v2

array([-4, -2,  0,  2,  4])

## Exceptions (addition with a scalar)

In [38]:
m1 + 1

array([[ 2,  3,  4],
       [-3, -4, -5]])

In [39]:
v1 + 1

array([2, 3, 4, 5, 6])

In [40]:
m1 + np.array([1])

array([[ 2,  3,  4],
       [-3, -4, -5]])

In [41]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])

## Transposing Matrices

In [42]:
A = np.array([[1,3,5],[2,4,6]])
A

array([[1, 3, 5],
       [2, 4, 6]])

In [43]:
A.T

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
B = np.array([[8,10],[-2,-6]])
B

array([[ 8, 10],
       [-2, -6]])

In [45]:
B.T

array([[ 8, -2],
       [10, -6]])

In [46]:
C = np.array([[2,3],[8,6],[-1,-2],[20,2]])
C

array([[ 2,  3],
       [ 8,  6],
       [-1, -2],
       [20,  2]])

In [47]:
C.T

array([[ 2,  8, -1, 20],
       [ 3,  6, -2,  2]])

## Transposing Scalars

In [48]:
s = np.array([8])

In [49]:
s.T

array([8])

## Transposing Vectors

In [50]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [51]:
v.T

array([1, 2, 3])

In [52]:
v.shape

(3,)

In [53]:
v_reshaped = v.reshape(1,3)
v_reshaped

array([[1, 2, 3]])

In [54]:
v_reshaped.T

array([[1],
       [2],
       [3]])

## Dot Product

In [55]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [56]:
np.dot(x,y)

32

In [57]:
u = np.array([0,2,4,6])
v = np.array([-3,-2,-1,0])

In [58]:
np.dot(u,v)

-8

## Scalar * Scalar

In [59]:
np.dot(2,4)

8

In [60]:
np.dot(-1,7)

-7

## Scalar * Vector

In [61]:
x

array([1, 2, 3])

In [62]:
5*x

array([ 5, 10, 15])

## Scalar * Matrix

In [63]:
3*A

array([[ 3,  9, 15],
       [ 6, 12, 18]])

## Matrix * Matrix

In [64]:
A = np.array([[1,2,3],[9,8,7]])
A

array([[1, 2, 3],
       [9, 8, 7]])

In [65]:
B = np.array([[2,4],[-8,-6],[3,5]])
B

array([[ 2,  4],
       [-8, -6],
       [ 3,  5]])

In [66]:
np.dot(A,B)

array([[ -5,   7],
       [-25,  23]])