# Machine Learning Linear Algebra

In [1]:
# Libraries
import numpy as np

In [2]:
# Linear Algebra
# Matrix
A = np.matrix([[1, 2],[3, 4]])
A

matrix([[1, 2],
        [3, 4]])

In [3]:
B = np.array([[5,6],[7,8]])
B

array([[5, 6],
       [7, 8]])

In [4]:
A+B

matrix([[ 6,  8],
        [10, 12]])

In [5]:
A-B

matrix([[-4, -4],
        [-4, -4]])

In [6]:
A*B

matrix([[19, 22],
        [43, 50]])

In [7]:
A.T

matrix([[1, 3],
        [2, 4]])

In [8]:
B.transpose()

array([[5, 7],
       [6, 8]])

In [9]:
A.T * B.T

matrix([[23, 31],
        [34, 46]])

In [10]:
# (AB).T = B.T*A.T
(A*B).T

matrix([[19, 43],
        [22, 50]])

In [11]:
B.T * A.T

matrix([[19, 43],
        [22, 50]])

In [12]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
x = np.array([2,2,3]).reshape(3,1)
x

array([[2],
       [2],
       [3]])

In [14]:
b = A.dot(x)
b

array([[15],
       [36]])

In [15]:
# Determinant of a Matrix
A = np.matrix([[6,1,1],[4,-2,5],[2,8,7]])
A

matrix([[ 6,  1,  1],
        [ 4, -2,  5],
        [ 2,  8,  7]])

In [16]:
np.linalg.det(A)

-306.0

In [17]:
A = np.matrix([[4,3],[3,2]])
np.linalg.det(A)

-1.0

In [18]:
A = np.matrix([[4,3],[3,2]])
A

matrix([[4, 3],
        [3, 2]])

In [19]:
A.I

matrix([[-2.,  3.],
        [ 3., -4.]])

In [20]:
# Inverse of a Matrix
A1 = np.linalg.inv(A)
A1

matrix([[-2.,  3.],
        [ 3., -4.]])

In [21]:
I = A*A.I
I

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [22]:
I = A.I*A
I

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [23]:
A.T.I

matrix([[-2.,  3.],
        [ 3., -4.]])

In [24]:
A.I.T

matrix([[-2.,  3.],
        [ 3., -4.]])

In [25]:
# Pseudo Inverse Matrix
A = np.matrix([[1,1,1,1],[5,7,7,9]])
A

matrix([[1, 1, 1, 1],
        [5, 7, 7, 9]])

In [26]:
A.T.dot(A)

matrix([[26, 36, 36, 46],
        [36, 50, 50, 64],
        [36, 50, 50, 64],
        [46, 64, 64, 82]])

In [27]:
A * A.T # is not invertible

matrix([[  4,  28],
        [ 28, 204]])

In [28]:
(A*A.T).I

matrix([[ 6.375, -0.875],
        [-0.875,  0.125]])

In [29]:
A.T*(A*A.T).I

matrix([[  2.00000000e+00,  -2.50000000e-01],
        [  2.50000000e-01,  -1.11022302e-16],
        [  2.50000000e-01,  -1.11022302e-16],
        [ -1.50000000e+00,   2.50000000e-01]])

In [30]:
np.linalg.pinv(A) #Faster Calculations for Pseudo Inverse Matrix

matrix([[  2.00000000e+00,  -2.50000000e-01],
        [  2.50000000e-01,   4.85722573e-17],
        [  2.50000000e-01,   4.85722573e-17],
        [ -1.50000000e+00,   2.50000000e-01]])

In [31]:
# Rank of matrix
from numpy.linalg import matrix_rank

X = np.matrix([[1,2,4,4],[3,4,8,0]])
X
matrix_rank(X)

2

In [32]:
# Eigenvalues and Eigenvectors
from numpy import linalg as LA
A = np.array([[1,2,3],[3,4,5],[6,7,8]])
w, v = LA.eig(A)
print(w)

[  1.40663730e+01  -1.06637298e+00  -8.53823664e-16]


In [33]:
u = v[:,1]
print(u)

[ 0.74442863  0.19070122 -0.63988988]


In [34]:
lam = w[1]
print(lam)

-1.06637297521


In [35]:
print(np.dot(A,u))

[-0.79383857 -0.20335863  0.68236128]


In [36]:
print(lam*u)

[-0.79383857 -0.20335863  0.68236128]


In [37]:
# Eigendecomposition
from numpy.linalg import eig

A = np.array([[0, 1, 2], [3, 4, 5], [-1, -2, -3]])
print(A)
print('____________________________________________________________')

# Calculations
values, vectors = eig(A)
print('eigenvalues:')
print(values)
print('____________________________________________________________')
print('eigenvetors:')
print(vectors)

[[ 0  1  2]
 [ 3  4  5]
 [-1 -2 -3]]
____________________________________________________________
eigenvalues:
[  2.30277564e+00  -3.56919355e-16  -1.30277564e+00]
____________________________________________________________
eigenvetors:
[[-0.08497018 -0.40824829 -0.81799057]
 [-0.92688249  0.81649658 -0.07498772]
 [ 0.36560761 -0.40824829  0.57032295]]


In [38]:
# Confirm the first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)
print(B==C)

[-0.19566726 -2.13440241  0.84191231]
[-0.19566726 -2.13440241  0.84191231]
[ True  True  True]


In [39]:
if B.all() == C.all():
    print('Same results vector')
else:
    print('They are not the same results')

Same results vector
